language: go

before_install:
  - go get -v golang.org/x/tools/cmd/cover
  - go get -v github.com/axw/gocov/gocov
  - go get -v github.com/mattn/goveralls

# skip `go get` to ensure vendored dependencies are used for testing
install: /bin/true

script:
  - go test -v ./... -race
  - go test -covermode=atomic ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
  - go install
  - lingo check ./...
