version: "{build}"

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.10.1

clone_folder: c:\gopath\src\github.com\s2gatev\lingo

init:
  - git config --global core.autocrlf input

install:
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
  - set PATH=%PATH%;c:\go\bin;%GOPATH%\bin
  - go version
  - go env

test_script:
  - go test ./...

build: false
deploy: false
