[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "golang.org/x/tools"
  revision = "96caea41033df6f8c3974c845ab094f8ec3bd345"

[[constraint]]
  name = "github.com/alecthomas/chroma"
  version = "0.4.0"

[[constraint]]
  name = "github.com/uber-go/mapdecode"
  version = "1.0.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.1.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
